<a href="https://colab.research.google.com/github/haituly/Apply-Math-and-Machine-Learning-in-Python/blob/main/Define_Several_Formulations_of_Gaussian_Elimination_Without_Pivoting_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Using slices to perform forward and backward substitution.
# We define lowerfSub(A,b) function to perform row oriented forward substitution for lower triangular systems using only one for loop.
def lowerfSub(A,b):
  n=len(A)
  x=np.zeros(n)
  x[0]=b[0]/A[0,0]
  for i in range(1,n):
    x[i]=1/A[i,i]*(b[i]-np.dot(A[i,0:i],x[0:i]))
  return x

In [ ]:
# We validate code using matrix
import numpy as np
B=[[1,0,0,0],[2,3,0,0],[1,-1,9,0],[2,0,3,1]]
A=np.matrix(B)
b=np.random.rand(4)
print(A)
print(b)
print(lowerfSub(A,b))
x=lowerfSub(A,b)
np.allclose(A@x,b)

[[ 1  0  0  0]
 [ 2  3  0  0]
 [ 1 -1  9  0]
 [ 2  0  3  1]]
[0.70751247 0.39621394 0.90197785 0.06087386]
[ 0.70751247 -0.33960366 -0.01612648 -1.30577165]


True

In [ ]:
# We also define upperbSub(A,b) functions like the one above to perform row oriented backward substitution.
def upperbSub(A,b):
  n=len(A)
  x=np.zeros(n)
  x[n-1]=b[n-1]/A[n-1,n-1]
  for i in range(1,n):
     x[n-1-i]=1/A[n-1-i,n-1-i]*(b[n-1-i]-np.dot(A[n-1-i,n-i:],x[n-i:]))
  return x
# Validate our code
np.allclose(A@x,b)

True

Define Inner Product Formulation of Gaussian Elimination

In [ ]:
# We write a function innerGEWP(A) containing only one for loop which takes in an n × n matrix and uses the inner product form of Gaussian elimination without pivoting to compute its LU decomposition.
def innerGEWP(A):
  B=np.zeros((len(A),len(A)))
  B[0,:]=A[0,:]
  B[1:,0]=A[1:,0]/A[0,0]
  for i in range(len(A)):
    B[i,i:]=A[i,i:]-B[i,:i]@B[:i,i:]
    B[i+1:,i]=1/B[i,i]*(A[i+1:,i]-B[i+1:,:i]@B[:i,i])
  return B

# Define a Split Function to split the output of innerGEWP function into n x n matrices L and U.
def split(A):
  U=np.zeros((len(A),len(A)))
  L=np.eye(len(A))
  for i in range(len(A)):
     U[i,i:]=A[i,i:]
     L[i+1:,i]=A[i+1:,i]
  return L, U

# Validate our code
A=np.random.rand(20,20)
L,U=split(innerGEWP(A))
np.allclose(L@U,A)

True

In [ ]:
# Define Outer Product Formulation of Gaussian Elimination.
def outerGEWP(A):
  B = np.copy(A)
  for i in range(len(A)-1):
    B[i+1:,i]=B[i+1:,i]/B[i,i]
    B[i+1:,i+1:]=B[i+1:,i+1:]-np.outer(B[i+1:,i],B[i,i+1:])
  return B

# Validate our code
A=np.random.rand(20,20)
L,U=split(outerGEWP(A))
np.allclose(L@U,A)

True